import { LoadingBar } from "./loadingBar";

it("creates a loading bar animation", () => {
  expect(
LoadingBar({
  getMilliseconds: () => 0,
  getSeconds: () => 0,
  getMinutes: () => 0,
  getHours: () => 0,
  getDay: () => 0 })).

toMatchInlineSnapshot(`
<article>
  <h2>
    Loading Bar
  </h2>
  <p>
    
        The three clock hands are replaced with loading bars.
        The first bar shows progress from midnight to midnight.
        The second bar shows progress in the current hour.
        The third bar shows progress in the current minute.
      
  </p>
  <svg
    viewBox="-100 -100 200 200"
  >
    <g>
      <rect
        fill="green"
        height="50"
        stroke="green"
        stroke-width="2"
        width="100"
        x="-90"
        y="-95"
      >
        <animate
          attributeName="width"
          begin="0s;hoursecond.end"
          dur="86400s"
          id="hourfirst"
          values="0;180"
        />
        <animate
          attributeName="width"
          begin="hourfirst.end"
          dur="0s"
          id="hoursecond"
          values="0;0"
        />
      </rect>
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="-82.5"
        x2="-82.5"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="-75"
        x2="-75"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="-67.5"
        x2="-67.5"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="-60"
        x2="-60"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="-52.5"
        x2="-52.5"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="-45"
        x2="-45"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="-37.5"
        x2="-37.5"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="-30"
        x2="-30"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="-22.5"
        x2="-22.5"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="-15"
        x2="-15"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="-7.5"
        x2="-7.5"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="0"
        x2="0"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="7.5"
        x2="7.5"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="15"
        x2="15"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="22.5"
        x2="22.5"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="30"
        x2="30"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="37.5"
        x2="37.5"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="45"
        x2="45"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="52.5"
        x2="52.5"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="60"
        x2="60"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="67.5"
        x2="67.5"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="75"
        x2="75"
        y1="-95"
        y2="-90"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="82.5"
        x2="82.5"
        y1="-95"
        y2="-90"
      />
      <rect
        fill="transparent"
        height="50"
        stroke="black"
        stroke-width="2"
        width="180"
        x="-90"
        y="-95"
      />
    </g>
    <g>
      <rect
        fill="green"
        height="50"
        stroke="green"
        stroke-width="2"
        width="100"
        x="-90"
        y="-25"
      >
        <animate
          attributeName="width"
          begin="0s;minutesecond.end"
          dur="3600s"
          id="minutefirst"
          values="0;180"
        />
        <animate
          attributeName="width"
          begin="minutefirst.end"
          dur="0s"
          id="minutesecond"
          values="0;0"
        />
      </rect>
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="-75"
        x2="-75"
        y1="-25"
        y2="-20"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="-60"
        x2="-60"
        y1="-25"
        y2="-20"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="-45"
        x2="-45"
        y1="-25"
        y2="-20"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="-30"
        x2="-30"
        y1="-25"
        y2="-20"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="-15"
        x2="-15"
        y1="-25"
        y2="-20"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="0"
        x2="0"
        y1="-25"
        y2="-20"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="15"
        x2="15"
        y1="-25"
        y2="-20"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="30"
        x2="30"
        y1="-25"
        y2="-20"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="45"
        x2="45"
        y1="-25"
        y2="-20"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="60"
        x2="60"
        y1="-25"
        y2="-20"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="75"
        x2="75"
        y1="-25"
        y2="-20"
      />
      <rect
        fill="transparent"
        height="50"
        stroke="black"
        stroke-width="2"
        width="180"
        x="-90"
        y="-25"
      />
    </g>
    <g>
      <rect
        fill="green"
        height="50"
        stroke="green"
        stroke-width="2"
        width="100"
        x="-90"
        y="45"
      >
        <animate
          attributeName="width"
          begin="0s;secondsecond.end"
          dur="60s"
          id="secondfirst"
          values="0;180"
        />
        <animate
          attributeName="width"
          begin="secondfirst.end"
          dur="0s"
          id="secondsecond"
          values="0;0"
        />
      </rect>
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="-75"
        x2="-75"
        y1="45"
        y2="50"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="-60"
        x2="-60"
        y1="45"
        y2="50"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="-45"
        x2="-45"
        y1="45"
        y2="50"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="-30"
        x2="-30"
        y1="45"
        y2="50"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="-15"
        x2="-15"
        y1="45"
        y2="50"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="0"
        x2="0"
        y1="45"
        y2="50"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="15"
        x2="15"
        y1="45"
        y2="50"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="30"
        x2="30"
        y1="45"
        y2="50"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="45"
        x2="45"
        y1="45"
        y2="50"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="60"
        x2="60"
        y1="45"
        y2="50"
      />
      <line
        stroke="black"
        stroke-linecap="round"
        stroke-width="1"
        x1="75"
        x2="75"
        y1="45"
        y2="50"
      />
      <rect
        fill="transparent"
        height="50"
        stroke="black"
        stroke-width="2"
        width="180"
        x="-90"
        y="45"
      />
    </g>
  </svg>
</article>
`);
});
